---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    # Replace $USER with your actual cPanel username in the line above
    - /bin/cp -R python_backend/* $DEPLOYPATH
    - /bin/cp python_backend/.htaccess $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/build/client
    - /bin/cp -R build/* $DEPLOYPATH/build/
    - /bin/cp -R client/public/* $DEPLOYPATH/build/client/
