import React from 'react';
import { BarChart3, AlertCircle, ShieldAlert, Database, Clock, Zap, Search, PieChart } from 'lucide-react';
import SolutionPageLayout from '@/components/SolutionPageLayout';
import { TermTechTooltip, FeatureTechTooltip, InfoTechTooltip } from '@/components/ui/tech-tooltips';

const SiemPage = () => {
  return (
    <SolutionPageLayout
      title="Security Information & Event Management (SIEM)"
      category="Security Technology Solutions"
      description="Advanced SIEM solutions that provide real-time analysis of security alerts generated by applications and network hardware."
      heroIcon={<BarChart3 className="h-12 w-12 text-[hsl(var(--secondary))]" />}
      problem={
        <div className="space-y-4">
          <p>
            Organizations face an overwhelming volume of security events and logs from numerous sources, making it impossible to manually detect threats effectively. Without centralized visibility, critical security incidents often go unnoticed until damage occurs.
          </p>
          <p>
            Many businesses struggle with <TermTechTooltip term="Alert Fatigue" definition="The desensitization that occurs when security staff are exposed to a large number of frequent alerts, causing important alerts to be missed or ignored.">alert fatigue</TermTechTooltip> and lack the capabilities to correlate events across different systems to identify sophisticated attack patterns that bypass individual security controls.
          </p>
          <p>
            Regulatory compliance requirements increasingly demand comprehensive log management and security monitoring, creating additional pressure to implement effective security monitoring solutions.
          </p>
        </div>
      }
      solution={
        <div className="space-y-4">
          <p>
            Our <FeatureTechTooltip featureTitle="SIEM Platform" featureDescription="A comprehensive security solution that combines Security Information Management (SIM) and Security Event Management (SEM) to provide real-time analysis of security alerts." icon={<BarChart3 className="w-4 h-4 mt-0.5 text-[hsl(var(--secondary))]" />}>SIEM solution</FeatureTechTooltip> provides a centralized system that ingests log and event data from across your entire IT environment, including networks, servers, applications, and security devices.
          </p>
          <p>
            Using advanced analytics and <InfoTechTooltip infoTitle="Machine Learning & AI" infoText="Our SIEM solutions incorporate advanced machine learning algorithms that continuously learn from your environment to improve threat detection accuracy and reduce false positives.">machine learning capabilities</InfoTechTooltip>, our platform correlates seemingly unrelated events to identify complex attack patterns and provides actionable alerts on genuine security incidents.
          </p>
          <p>
            The solution includes customizable dashboards, automated incident response workflows, and comprehensive reporting tools to simplify compliance management and provide clear visibility into your security posture.
          </p>
        </div>
      }
      features={[
        {
          icon: <Database className="h-6 w-6 text-[hsl(var(--secondary))]" />,
          title: "Log Collection & Aggregation",
          description: "Centralized collection and normalization of log data from across your entire IT infrastructure, including on-premises and cloud environments."
        },
        {
          icon: <Search className="h-6 w-6 text-[hsl(var(--secondary))]" />,
          title: "Real-time Threat Detection",
          description: "Continuous monitoring and analysis of security events with alert generation for potential threats based on advanced correlation rules."
        },
        {
          icon: <AlertCircle className="h-6 w-6 text-[hsl(var(--secondary))]" />,
          title: "Security Incident Response",
          description: "Automated response workflows and case management tools to accelerate incident investigation and resolution."
        },
        {
          icon: <PieChart className="h-6 w-6 text-[hsl(var(--secondary))]" />,
          title: "Interactive Dashboards",
          description: "Customizable visualization tools providing real-time insights into security events, trends, and overall risk posture."
        },
        {
          icon: <Clock className="h-6 w-6 text-[hsl(var(--secondary))]" />,
          title: "User & Entity Behavior Analytics",
          description: "Advanced behavioral analysis to detect anomalous activities that may indicate compromised accounts or insider threats."
        },
        {
          icon: <ShieldAlert className="h-6 w-6 text-[hsl(var(--secondary))]" />,
          title: "Threat Intelligence Integration",
          description: "Incorporation of global threat feeds to enhance detection capabilities and provide context for security alerts."
        }
      ]}
      benefits={[
        {
          title: "Enhanced Threat Detection",
          description: "Identify sophisticated attacks and security breaches that might otherwise go unnoticed through advanced correlation and analytics."
        },
        {
          title: "Reduced Response Time",
          description: "Decrease the time between initial compromise and detection, limiting potential damage and data loss from security incidents."
        },
        {
          title: "Simplified Compliance",
          description: "Meet regulatory requirements for security monitoring, log management, and incident reporting with built-in compliance frameworks."
        },
        {
          title: "Operational Efficiency",
          description: "Streamline security operations through automation, prioritized alerting, and centralized management of security events."
        },
        {
          title: "Comprehensive Visibility",
          description: "Gain a holistic view of your security posture across the entire IT environment through unified monitoring and reporting."
        },
        {
          title: "Forensic Investigation",
          description: "Maintain detailed security logs and audit trails to support post-incident analysis and potential legal proceedings."
        }
      ]}
      animationSvg={
        <svg width="100%" height="100%" viewBox="0 0 800 600" fill="none" xmlns="http://www.w3.org/2000/svg" className="max-w-lg mx-auto">
          {/* Central SIEM Hub */}
          <circle cx="400" cy="300" r="80" fill="transparent" stroke="hsl(var(--secondary))" strokeWidth="2" />
          <text x="400" y="300" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--secondary))" fontSize="16" fontWeight="bold">SIEM</text>
          
          {/* Connected systems */}
          <g>
            {/* System 1 - Server */}
            <rect x="140" y="100" width="60" height="80" rx="5" fill="transparent" stroke="hsl(var(--primary))" strokeWidth="1.5" />
            <text x="170" y="85" textAnchor="middle" fill="hsl(var(--primary))" fontSize="12">Servers</text>
            
            {/* System 2 - Network */}
            <rect x="600" y="100" width="60" height="80" rx="5" fill="transparent" stroke="hsl(var(--primary))" strokeWidth="1.5" />
            <text x="630" y="85" textAnchor="middle" fill="hsl(var(--primary))" fontSize="12">Network</text>
            
            {/* System 3 - Applications */}
            <rect x="140" y="420" width="60" height="80" rx="5" fill="transparent" stroke="hsl(var(--primary))" strokeWidth="1.5" />
            <text x="170" y="515" textAnchor="middle" fill="hsl(var(--primary))" fontSize="12">Applications</text>
            
            {/* System 4 - Security Devices */}
            <rect x="600" y="420" width="60" height="80" rx="5" fill="transparent" stroke="hsl(var(--primary))" strokeWidth="1.5" />
            <text x="630" y="515" textAnchor="middle" fill="hsl(var(--primary))" fontSize="12">Security</text>
          </g>
          
          {/* Data flow lines */}
          <g>
            <path 
              d="M200,140 C280,180 320,220 400,300" 
              stroke="hsl(var(--primary))" 
              strokeWidth="1.5"
              strokeDasharray="5,5"
              className="animate-dash"
            />
            <path 
              d="M600,140 C520,180 480,220 400,300" 
              stroke="hsl(var(--primary))" 
              strokeWidth="1.5"
              strokeDasharray="5,5"
              className="animate-dash"
              style={{ animationDelay: '0.5s' }}
            />
            <path 
              d="M200,460 C280,420 320,380 400,300" 
              stroke="hsl(var(--primary))" 
              strokeWidth="1.5"
              strokeDasharray="5,5"
              className="animate-dash"
              style={{ animationDelay: '1s' }}
            />
            <path 
              d="M600,460 C520,420 480,380 400,300" 
              stroke="hsl(var(--primary))" 
              strokeWidth="1.5"
              strokeDasharray="5,5"
              className="animate-dash"
              style={{ animationDelay: '1.5s' }}
            />
          </g>
          
          {/* Data packets */}
          <g className="animate-pulse" style={{ animationDuration: '2s' }}>
            <circle cx="240" cy="190" r="5" fill="hsl(var(--primary))" />
            <circle cx="560" cy="190" r="5" fill="hsl(var(--primary))" />
            <circle cx="240" cy="410" r="5" fill="hsl(var(--primary))" />
            <circle cx="560" cy="410" r="5" fill="hsl(var(--primary))" />
          </g>
          
          {/* Dashboard elements in the SIEM */}
          <rect x="375" y="280" width="50" height="10" rx="2" fill="hsl(var(--secondary))" fillOpacity="0.6" />
          <rect x="375" y="295" width="50" height="10" rx="2" fill="hsl(var(--secondary))" fillOpacity="0.6" />
          <rect x="375" y="310" width="50" height="10" rx="2" fill="hsl(var(--secondary))" fillOpacity="0.6" />
          
          <style jsx>{`
            @keyframes dash {
              to {
                stroke-dashoffset: 100;
              }
            }
            .animate-dash {
              animation: dash 5s linear infinite;
            }
          `}</style>
        </svg>
      }
      relatedSolutions={[
        {
          title: "Endpoint Detection & Response",
          link: "/solutions/edr"
        },
        {
          title: "Vulnerability Management",
          link: "/solutions/vulnerability-management"
        },
        {
          title: "Email Security Solutions",
          link: "/solutions/email-security"
        },
        {
          title: "Data Loss Prevention",
          link: "/solutions/dlp"
        }
      ]}
    />
  );
};

export default SiemPage;